apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: team-app-projects
  namespace: argocd
spec:
  goTemplate: true
  generators:
    - git:
        repoURL: 'https://github.com/omri2003/namespace-factory-proj.git'
        revision: HEAD
        directories:
          - path: envs/development/*
  template:
    metadata:
      name: 'project-{{index .path.segments 2}}'
    spec:
      project: default 
      source:
        repoURL: 'https://github.com/omri2003/namespace-factory-proj.git'
        targetRevision: HEAD
        path: project-template
      destination:
        server: https://kubernetes.default.svc
        namespace: argocd
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
