apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: team-app-projects
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-20"
spec:
  goTemplate: true
  generators:
    - git:
        repoURL: 'https://github.com/omri2003/namespace-factory-proj.git'
        revision: main
        directories:
          - path: envs/*/*
  template:
    metadata:
      # Naming convention: [team]-[env]-project-deployer
      name: '{{index .path.segments 2}}-{{index .path.segments 1}}-project-deployer'
      annotations:
        argocd.argoproj.io/sync-wave: "-20"
    spec:
      project: default
      source:
        repoURL: 'https://github.com/omri2003/namespace-factory-proj.git'
        targetRevision: main
        path: charts/project-template
        helm:
          parameters:
            - name: "env"
              value: '{{index .path.segments 1}}'
            - name: "team"
              value: '{{index .path.segments 2}}'
      destination:
        server: https://kubernetes.default.svc
        namespace: argocd
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
