apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: project-{{ .Values.teamName }}
  namespace: argocd
spec:
  description: "Governance for Team {{ .Values.teamName }}"
  sourceRepos: ["*"]
  destinations:
  - namespace: '*-{{ .Values.teamName }}-*'
    server: https://kubernetes.default.svc
  clusterResourceWhitelist:
  - group: ''
    kind: Namespace
