apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: project-${TEAM_NAME}
  namespace: argocd
spec:
  description: "Governance for Team ${TEAM_NAME}"
  sourceRepos: ["*"]
  destinations:
  - namespace: '*-${TEAM_NAME}-*'
    server: https://kubernetes.default.svc
  clusterResourceWhitelist:
  - group: ''
    kind: Namespace
