apiVersion: v1
kind: ResourceQuota
metadata:
  name: basic-resource-quota
spec:
  hard:
    requests.cpu: "2"
    requests.memory: 4Gi
    limits.cpu: "4"
    limits.memory: 8Gi
    
    # Can further limit the team using the following (but its ROI is quite low, since its only an exercise ill leave it here).
    pods: "20"
    services: "5"
    persistentvolumeclaims: "4"
    configmaps: "10"
    secrets: "10"
