apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: roleBinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: edit
subjects:
  - kind: Group
    name: "$TEAM_NAME"
    apiGroup: rbac.authorization.k8s.io
  - kind: ServiceAccount
    name: pipeline-deployer
    namespace: "$PROJECT_NAMESPACE"
